version: "3"
services:
  web:
    build: .
    image:  laravel:7.4-cli
    container_name: laravelHelloWorld
    command: sh -c "cd /home/ubuntu/laravelHelloWorld && php artisan serve --host=0.0.0.0"
    tty: true
    volumes:
      - "./../:/home/ubuntu/laravelHelloWorld"
    ports:
      - 80:8000
